<?php

/**
 * Recurring task definitions (owner-managed in Settings).
 *
 * Two kinds:
 *  - "monthly": fully editable — title, assignee, days of month. The daily cron
 *    adds the task to the assignee's to-dos on the chosen days.
 *  - "system": generated by dedicated logic (e.g. post-course tasks). Schedule is
 *    fixed; only the title text is editable. Shown read-only otherwise.
 */

define('RECURRING_FILE',       dirname(__DIR__) . '/data/recurring_tasks.json');
define('RECURRING_STATE_FILE', dirname(__DIR__) . '/data/recurring_done.json');

/** @return list<array<string,mixed>> */
function clp_default_recurring(): array
{
    $sched = 'A doua zi după fiecare curs';
    return [
        ['id' => 'sys_pc_1', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Adaugă foto-video Drive de la cursul {curs}', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs. {curs} = numele cursului.'],
        ['id' => 'sys_pc_2', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Modifică denumirile videoclipurilor', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs.'],
        ['id' => 'sys_pc_3', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Cere factură {speaker}', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs. {speaker} = speakerul cursului.'],
        ['id' => 'sys_pc_4', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Trimite formular feedback {speaker}', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs. {speaker} = speakerul cursului.'],
        ['id' => 'sys_publish', 'type' => 'system', 'system_key' => 'course_published', 'assigned_to' => 'andy',
         'title' => 'Adaugă cursul {curs} pe [Off the Couch](https://offthecouch.city/) și [Mellon](https://mellon.life/discover)',
         'schedule' => 'Când un curs primește link',
         'description' => 'Generat automat lui Andy când un curs capătă link LiveTickets. {curs} = numele cursului.'],
    ];
}

/** Strip the "Curs la Pahar - ... // date" decoration from a course title. */
function clp_course_short_name(string $t): string
{
    $t = preg_replace('/^\s*Curs la Pahar\s*[-–]\s*/u', '', $t);
    $t = preg_replace('#\s*//.*$#u', '', $t);
    return trim($t);
}

/**
 * Add Andy a "publish on partner sites" task the first time a course gains a
 * LiveTickets link. Idempotent via a state file; the very first run only seeds
 * the state (no tasks) so existing linked courses don't flood the list.
 *
 * @return list<string> names of courses that got a new task
 */
function clp_process_course_publish_tasks(): array
{
    $tpl = null;
    foreach (clp_load_recurring() as $t) {
        if (($t['system_key'] ?? '') === 'course_published') { $tpl = $t; break; }
    }
    if (!$tpl || trim((string)($tpl['title'] ?? '')) === '') return [];

    require_once __DIR__ . '/courses.php';
    require_once __DIR__ . '/todos.php';

    $courses    = clp_load_courses_from_json();
    $state_file = dirname(__DIR__) . '/data/course_publish_done.json';
    $first_run  = !is_file($state_file);
    $done       = $first_run ? [] : (json_decode((string)file_get_contents($state_file), true) ?: []);

    $added = [];
    foreach ($courses as $c) {
        $id = (string)($c['id'] ?? '');
        $has_link = trim((string)($c['livetickets_url'] ?? '')) !== '';
        if ($id === '' || !$has_link || in_array($id, $done, true)) continue;

        if (!$first_run) {
            $name  = clp_course_short_name((string)($c['title'] ?? ''));
            $title = str_replace('{curs}', $name, (string)$tpl['title']);
            clp_add_todo($title, (string)($tpl['assigned_to'] ?? 'andy'), 'system');
            $added[] = $name;
        }
        $done[] = $id;
    }

    file_put_contents($state_file, json_encode(array_values(array_unique($done)), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
    return $added;
}

/** @return list<array<string,mixed>> */
function clp_load_recurring(): array
{
    if (!is_file(RECURRING_FILE)) {
        $def = clp_default_recurring();
        clp_save_recurring($def);
        return $def;
    }
    $data = json_decode((string)file_get_contents(RECURRING_FILE), true);
    if (!is_array($data)) return clp_default_recurring();

    // Make sure the built-in system tasks are never lost (re-add any missing).
    $have = array_column($data, 'id');
    foreach (clp_default_recurring() as $sys) {
        if (!in_array($sys['id'], $have, true)) $data[] = $sys;
    }
    return $data;
}

function clp_save_recurring(array $items): bool
{
    return file_put_contents(
        RECURRING_FILE,
        json_encode(array_values($items), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE),
        LOCK_EX
    ) !== false;
}

/** Monthly (editable) tasks only. @return list<array<string,mixed>> */
function clp_recurring_monthly(): array
{
    return array_values(array_filter(clp_load_recurring(), fn($t) => ($t['type'] ?? '') === 'monthly'));
}

/** System tasks only. @return list<array<string,mixed>> */
function clp_recurring_system(): array
{
    return array_values(array_filter(clp_load_recurring(), fn($t) => ($t['type'] ?? '') === 'system'));
}

/** Post-course title templates (for the course cron). @return list<array{title:string,assigned_to:string}> */
function clp_recurring_post_course(): array
{
    $out = [];
    foreach (clp_load_recurring() as $t) {
        if (($t['type'] ?? '') === 'system' && ($t['system_key'] ?? '') === 'post_course') {
            $title = trim((string)($t['title'] ?? ''));
            if ($title !== '') {
                $out[] = ['title' => $title, 'assigned_to' => (string)($t['assigned_to'] ?? 'andy')];
            }
        }
    }
    return $out;
}

function clp_recurring_new_id(): string
{
    return 'rec_' . bin2hex(random_bytes(6));
}
