<?php

/**
 * Recurring task definitions (owner-managed in Settings).
 *
 * Two kinds:
 *  - "monthly": fully editable — title, assignee, days of month. The daily cron
 *    adds the task to the assignee's to-dos on the chosen days.
 *  - "system": generated by dedicated logic (e.g. post-course tasks). Schedule is
 *    fixed; only the title text is editable. Shown read-only otherwise.
 */

define('RECURRING_FILE',       dirname(__DIR__) . '/data/recurring_tasks.json');
define('RECURRING_STATE_FILE', dirname(__DIR__) . '/data/recurring_done.json');

/** @return list<array<string,mixed>> */
function clp_default_recurring(): array
{
    $sched = 'A doua zi după fiecare curs';
    return [
        ['id' => 'sys_pc_1', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Adaugă foto-video Drive de la cursul {curs}', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs. {curs} = numele cursului.'],
        ['id' => 'sys_pc_2', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Modifică denumirile videoclipurilor', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs.'],
        ['id' => 'sys_pc_3', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Cere factură {speaker}', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs. {speaker} = speakerul cursului.'],
        ['id' => 'sys_pc_4', 'type' => 'system', 'system_key' => 'post_course', 'assigned_to' => 'andy',
         'title' => 'Trimite formular feedback {speaker}', 'schedule' => $sched,
         'description' => 'Generat automat lui Andy a doua zi după fiecare curs. {speaker} = speakerul cursului.'],
    ];
}

/** @return list<array<string,mixed>> */
function clp_load_recurring(): array
{
    if (!is_file(RECURRING_FILE)) {
        $def = clp_default_recurring();
        clp_save_recurring($def);
        return $def;
    }
    $data = json_decode((string)file_get_contents(RECURRING_FILE), true);
    if (!is_array($data)) return clp_default_recurring();

    // Make sure the built-in system tasks are never lost (re-add any missing).
    $have = array_column($data, 'id');
    foreach (clp_default_recurring() as $sys) {
        if (!in_array($sys['id'], $have, true)) $data[] = $sys;
    }
    return $data;
}

function clp_save_recurring(array $items): bool
{
    return file_put_contents(
        RECURRING_FILE,
        json_encode(array_values($items), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE),
        LOCK_EX
    ) !== false;
}

/** Monthly (editable) tasks only. @return list<array<string,mixed>> */
function clp_recurring_monthly(): array
{
    return array_values(array_filter(clp_load_recurring(), fn($t) => ($t['type'] ?? '') === 'monthly'));
}

/** System tasks only. @return list<array<string,mixed>> */
function clp_recurring_system(): array
{
    return array_values(array_filter(clp_load_recurring(), fn($t) => ($t['type'] ?? '') === 'system'));
}

/** Post-course title templates (for the course cron). @return list<array{title:string,assigned_to:string}> */
function clp_recurring_post_course(): array
{
    $out = [];
    foreach (clp_load_recurring() as $t) {
        if (($t['type'] ?? '') === 'system' && ($t['system_key'] ?? '') === 'post_course') {
            $title = trim((string)($t['title'] ?? ''));
            if ($title !== '') {
                $out[] = ['title' => $title, 'assigned_to' => (string)($t['assigned_to'] ?? 'andy')];
            }
        }
    }
    return $out;
}

function clp_recurring_new_id(): string
{
    return 'rec_' . bin2hex(random_bytes(6));
}
