// Port din lib/pnl_cheltuiala_emoji.php.

export const CHELTUIALA_EMOJI: Record<string, string> = {
  "Onorariu curs": "🎤",
  Banca: "🏦",
  "Impozit curs": "🏛️",
  Avans: "💰",
  "Decont personal": "🧾",
  Echipament: "💻",
  Contabilitate: "📊",
  "Google Workspace": "📧",
  Hosting: "🌐",
  AI: "🤖",
  Salariu: "👥",
  Altele: "📦",
  Dividende: "💵",
  "Taxe stat lunare": "📋",
  "World Class": "🏋️",
  Fotograf: "📷",
  Chirie: "🏠",
  "Rata PC": "🖥️",
  "Fast-food": "🍔",
  Teambuilding: "☘️",
  Fun: "🤘",
  Backlinks: "🔗",
};

export const CHELTUIALA_EMOJI_KEYWORDS: Record<string, string> = {
  chirie: "🏠",
  banca: "🏦",
  impozit: "🏛️",
  tax: "📋",
  salariu: "👥",
  hosting: "🌐",
  google: "📧",
  contabilit: "📊",
  echipament: "💻",
  onorariu: "🎤",
  foto: "📷",
  "world class": "🏋️",
  "fast-food": "🍔",
  mancare: "🍔",
  team: "☘️",
  dividend: "💵",
  avans: "💰",
  decont: "🧾",
  "rata pc": "🖥️",
  fun: "🤘",
  backlink: "🔗",
};
